export const projectRequestConfig = {
  enabled: true,
  id: 'project-request',
  tabLabel: 'Start a Project',
  mobileLabel: 'Start a Project',
  eyebrow: 'Project request',
  title: 'Send a project request.',
  description: 'Share the problem, the systems involved, your timeline, and what you want the finished solution to do.',
  websiteLabel: 'Website',
  serviceLabel: 'Service needed',
  budgetLabel: 'Budget range',
  timelineLabel: 'Timeline',
  messageLabel: 'Project details',
  messagePlaceholder: 'What are you doing manually now? What systems are involved? What do you want the finished solution to do?',
  consentLabel: 'You can contact me about this request.',
  submitLabel: 'Send Service Request',
  submittingLabel: 'Sending request…',
  successTitle: 'Request received.',
  successMessage: 'I have your project details and will review the right next step.',
  nextStepTitle: 'What happens next?',
  nextStepText: 'Your request is saved, organized by service type, and sent to me for review.',
  privacyText: 'By submitting, you are asking Justin DeMatteis to contact you about this project request.',
  errorMessage: 'Unable to submit your request right now.',
  closeLabel: 'Close',
  theme: {
    primary: '#2F6BFF',
    primaryHover: '#2458D8',
    primaryDark: '#1748BE',
  },
};
